export default [
    

        {
    "id":1,
    "image" :"https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRUvlTnSx_WS2A7K90s0TgCEBBtu_LZJZB_XJX-xQ4SWGTRdt0d",
    "certificate":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUP1wydOPDck6B8Wgeuguri9gedByAl1l4kw&usqp=CAU",
    "course" :"Academic English",
    "instructor":"Jacke Masito",
    "categories":"Language",
    "Rating":"5",
    "price":"Free",
    "description":"Lorem Ipsn gravida nibh vel velit auctor aliquet.Aenean sollicitudin, Nam nec tellus a odio tincidunt auctor a ornare odio.",
    "duration":"2 weeks",
    "lecture":"10",
    "quizzes" :"3",
    "percentage":"60",
    "maxRetake":"3",
    "certificateDescription":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut hendrerit odio, id suscipit urna."
    },
      
       {
    "id":2,
    "image" :"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTz9u79KeyplkZEqcfLEybKrGjTbznlo3ksEC5hg10Yc32bRTkt",
    "certificate":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUP1wydOPDck6B8Wgeuguri9gedByAl1l4kw&usqp=CAU",
    "course" :"PC Systems",
    "instructor":"Judith Stevens",
    "categories":" IT & Software",
    "Rating":"5",
    "price":"$80",
    "description":"Lorem Ipsn gravida nibh vel velit auctor aliquet.Aenean sollicitudin, Nam nec tellus a odio tincidunt auctor a ornare odio.",
    "duration":"3 weeks",
    "lecture":"13",
    "quizzes" :"4",
    "percentage":"60",
    "maxRetake":"3",
    "certificateDescription":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut hendrerit odio, id suscipit urna."
     },
    
        
    
        {
    "id":3,
    "image" :"https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQEW0X4Qrx0GSO6sipcqDj7EyTdTKfeWsH7kdqQT6JswT59HCdu",
    "certificate":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUP1wydOPDck6B8Wgeuguri9gedByAl1l4kw&usqp=CAU",
    "course" :"Web Technology",
    "instructor":"Judith Stevens",
    "categories":"IT & Software",
    "Rating":"5",
    "price":"Free",
    "description":"Lorem Ipsn gravida nibh vel velit auctor aliquet.Aenean sollicitudin, Nam nec tellus a odio tincidunt auctor a ornare odio.",
    "duration":"10 weeks",
    "lecture":"23",
    "quizzes" :"10",
    "percentage":"60",
    "maxRetake":"3",
    "certificateDescription":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut hendrerit odio, id suscipit urna."
    },
    
    {
    "id":4,
    "image" :"https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcS68QLOl7ZZ_PEZDtdkyKaSzzSkL0WNcBmOZI6kARmll5iggU3J",
    "certificate":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUP1wydOPDck6B8Wgeuguri9gedByAl1l4kw&usqp=CAU",
    "course" :"IT Foundations",
    "instructor":"Ana Murphy",
    "categories":"IT & Software",
    "Rating":"5",
    "price":"$45",
    "description":"Lorem Ipsn gravida nibh vel velit auctor aliquet.Aenean sollicitudin, Nam nec tellus a odio tincidunt auctor a ornare odio.",
    "duration":"12 weeks",
    "lecture":"40",
    "quizzes" :"9",
    "percentage":"60",
    "maxRetake":"3",
    "certificateDescription":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut hendrerit odio, id suscipit urna."
    },
    
    {
    "id":5,
    "image" :"https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTMr896oAvgIGI0_Jxy0o7ZL-oyOp-03n3hOrFr0jqDr6EUQyNm",
    "certificate":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUP1wydOPDck6B8Wgeuguri9gedByAl1l4kw&usqp=CAU",
    "course" :"HR Menagement",
    "instructor":"Richard Dune",
    "categories":"Business",
    "Rating":"5",
    "price":"$20",
    "description":"Lorem Ipsn gravida nibh vel velit auctor aliquet.Aenean sollicitudin, Nam nec tellus a odio tincidunt auctor a ornare odio.",
    "duration":"7 weeks",
    "lecture":"15",
    "quizzes" :"4",
    "percentage":"60",
    "maxRetake":"3",
    "certificateDescription":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut hendrerit odio, id suscipit urna."
    },
    
    {
    "id":6,
    "image" :"https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTux94PGCHX4OF8ZwsNvulhQ0_b_3RusiJhaB5K3enr2HmeNGV_",
    "certificate":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUP1wydOPDck6B8Wgeuguri9gedByAl1l4kw&usqp=CAU",
    "course" :"Modeling",
    "instructor":"Glen Anders",
    "categories":"Art & Design",
    "Rating":"5",
    "price":"$20",
    "description":"Lorem Ipsn gravida nibh vel velit auctor aliquet.Aenean sollicitudin, Nam nec tellus a odio tincidunt auctor a ornare odio.",
    "duration":"4 weeks",
    "lecture":"24",
    "quizzes" :"6",
    "percentage":"60",
    "maxRetake":"3",
    "certificateDescription":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut hendrerit odio, id suscipit urna."
    },
    
    
    {
    "id":7,
    "image" :"https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQTdVDL_yvxzGCYrt6ERxcNnEWXduGBJ3UldF1ltA8U6hhZsruA",
    "certificate":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUP1wydOPDck6B8Wgeuguri9gedByAl1l4kw&usqp=CAU",
    "course" :"Basic Marketing",
    "instructor":"Richard Dune",
    "categories":"Business",
    "Rating":"5",
    "price":"$40",
    "description":"Lorem Ipsn gravida nibh vel velit auctor aliquet.Aenean sollicitudin, Nam nec tellus a odio tincidunt auctor a ornare odio.",
    "duration":"6 weeks",
    "lecture":"21",
    "quizzes" :"8",
    "percentage":"60",
    "maxRetake":"3",
    "certificateDescription":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut hendrerit odio, id suscipit urna."
    },
    
    
    {
    "id":8,
    "image" :"https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQhSt_uoj4gCjAhlbCVJPGkyzGqK0jMfhs_L0Rw8OVNVaGIKS5z",
    "certificate":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUP1wydOPDck6B8Wgeuguri9gedByAl1l4kw&usqp=CAU",
    "course" :"Business English",
    "instructor":"Jack Stevens",
    "categories":"Language",
    "Rating":"5",
    "price":"$20",
    "description":"Lorem Ipsn gravida nibh vel velit auctor aliquet.Aenean sollicitudin, Nam nec tellus a odio tincidunt auctor a ornare odio.",
    "duration":"8 weeks",
    "lecture":"30",
    "quizzes" :"7",
    "percentage":"60",
    "maxRetake":"3",
    "certificateDescription":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut hendrerit odio, id suscipit urna."
    },
    
    {
    "id":9,
    "image" :"https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQEW0X4Qrx0GSO6sipcqDj7EyTdTKfeWsH7kdqQT6JswT59HCdu",
    "certificate":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUP1wydOPDck6B8Wgeuguri9gedByAl1l4kw&usqp=CAU",
    "course" :"Learn Spanish",
    "instructor":"Laura Rees",
    "categories":"Language",
    "Rating":"5",
    "price":"$20",
    "description":"Lorem Ipsn gravida nibh vel velit auctor aliquet.Aenean sollicitudin, Nam nec tellus a odio tincidunt auctor a ornare odio.",
    "duration":"9 weeks",
    "lecture":"20",
    "quizzes" :"5",
    "percentage":"60",
    "maxRetake":"3",
    "certificateDescription":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut hendrerit odio, id suscipit urna."
    },
    
    {
    "id":10,
    "image" :"https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTFgip32nOr_quS5x5QYxE5X5oegT_8ifyIDtDP1F2pbRtZfhPR",
    "certificate":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUP1wydOPDck6B8Wgeuguri9gedByAl1l4kw&usqp=CAU",
    "course" :"Web Security",
    "instructor":"Edy Bowman",
    "categories":"Programming Languages",
    "Rating":"5",
    "price":"Free",
    "description":"Lorem Ipsn gravida nibh vel velit auctor aliquet.Aenean sollicitudin, Nam nec tellus a odio tincidunt auctor a ornare odio.",
    "duration":"4 weeks",
    "lecture":"10",
    "quizzes" :"3",
    "percentage":"60",
    "maxRetake":"3",
    "certificateDescription":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut hendrerit odio, id suscipit urna."
    },
    
    {
    "id":11,
    "image" :"https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQCXWyGCLSJOvRvH-nbsjvyujQKAa2MNQ3PuWnLf41otZ-_QfcU",
    "certificate":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUP1wydOPDck6B8Wgeuguri9gedByAl1l4kw&usqp=CAU",
    "course" :"Design Principles",
    "instructor":"Sophy Janer",
    "categories":"Art & Design",
    "Rating":"5",
    "price":"Free",
    "description":"Lorem Ipsn gravida nibh vel velit auctor aliquet.Aenean sollicitudin, Nam nec tellus a odio tincidunt auctor a ornare odio.",
    "duration":"11 weeks",
    "lecture":"10",
    "quizzes" :"3",
    "percentage":"60",
    "maxRetake":"3",
    "certificateDescription":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut hendrerit odio, id suscipit urna."
    },
    
    {
    "id":12,
    "image" :"https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTi2Mmt4xl75TdRB1RROnnrq0Jsamce4I2dWPH8rMmc8_PCkVD1",
    "certificate":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUP1wydOPDck6B8Wgeuguri9gedByAl1l4kw&usqp=CAU",
    "course" :"Digital Leadership",
    "instructor":"Nicholas Butler",
    "categories":"Business",
    "Rating":"5",
    "price":"Free",
    "description":"Lorem Ipsn gravida nibh vel velit auctor aliquet.Aenean sollicitudin, Nam nec tellus a odio tincidunt auctor a ornare odio.",
    "duration":"2 weeks",
    "lecture":"10",
    "quizzes" :"3",
    "percentage":"60",
    "maxRetake":"3",
    "certificateDescription":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut hendrerit odio, id suscipit urna."
    },
    
    {
    "id":13,
    "image" :"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQP_HqjH9Q4eeEtuzeywQE6hWwi7YXyzOofZTwVcFKbiADnWHoQ",
    "certificate":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUP1wydOPDck6B8Wgeuguri9gedByAl1l4kw&usqp=CAU",
    "course" :"Logo Design",
    "instructor":"Nicholas Butler",
    "categories":"Art & Design",
    "Rating":"5",
    "price":"$20",
    "description":"Lorem Ipsn gravida nibh vel velit auctor aliquet.Aenean sollicitudin, Nam nec tellus a odio tincidunt auctor a ornare odio.",
    "duration":"21 weeks",
    "lecture":"100",
    "quizzes" :"13",
    "percentage":"60",
    "maxRetake":"3",
    "certificateDescription":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut hendrerit odio, id suscipit urna."
    },
    
    {
    "id":14,
    "image" :"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIlOub4BsMR-_IadJ4wHHrBUMu3ccp3dkHMCue4SxKAzRKFeQP",
    "certificate":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUP1wydOPDck6B8Wgeuguri9gedByAl1l4kw&usqp=CAU",
    "course" :"App Developer",
    "instructor":"Edy Bowman",
    "categories":"Programming Languages",
    "Rating":"5",
    "price":"Free",
    "description":"Lorem Ipsn gravida nibh vel velit auctor aliquet.Aenean sollicitudin, Nam nec tellus a odio tincidunt auctor a ornare odio.",
    "duration":"5 weeks",
    "lecture":"14",
    "quizzes" :"4",
    "percentage":"60",
    "maxRetake":"3",
    "certificateDescription":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut hendrerit odio, id suscipit urna."
    },
    
    {
    "id":15,
    "image" :"https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSq5GsZSVOe2XyJg8Xt6qTjU30w6YuoCiJ2vb93-I0gKNp3C1oY",
    "certificate":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUP1wydOPDck6B8Wgeuguri9gedByAl1l4kw&usqp=CAU",
    "course" :"Web Developer",
    "instructor":"Edy Bowman",
    "categories":"Programming Languages",
    "Rating":"5",
    "price":"Free",
    "description":"Lorem Ipsn gravida nibh vel velit auctor aliquet.Aenean sollicitudin, Nam nec tellus a odio tincidunt auctor a ornare odio.",
    "duration":"2 weeks",
    "lecture":"10",
    "quizzes" :"3",
    "percentage":"60",
    "maxRetake":"3",
    "certificateDescription":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut hendrerit odio, id suscipit urna."
    },
    
    {
    "id":16,
    "image" :"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMbJCbfhxdDcGex4_TD-cD5T5ynFtESFQY6-qfSniS2_3R57J5",
    "certificate":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUP1wydOPDck6B8Wgeuguri9gedByAl1l4kw&usqp=CAU",
    "course" :"English Grammar",
    "instructor":"Jill King",
    "categories":"Language",
    "Rating":"5",
    "price":"Free",
    "description":"Lorem Ipsn gravida nibh vel velit auctor aliquet.Aenean sollicitudin, Nam nec tellus a odio tincidunt auctor a ornare odio.",
    "duration":"10 weeks",
    "lecture":"30",
    "quizzes" :"7",
    "percentage":"60",
    "maxRetake":"3",
    "certificateDescription":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut hendrerit odio, id suscipit urna."
    },
    
    {
    "id":17,
    "image" :"https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQRmH5SBJW-lSaBvAoeNG16Cx4zRHAhZsxGVNOlF8w7aAVE1Zes",
    "certificate":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUP1wydOPDck6B8Wgeuguri9gedByAl1l4kw&usqp=CAU",
    "course" :"Vocabulary",
    "instructor":"Jill King",
    "categories":"Language",
    "Rating":"5",
    "price":"$20",
    "description":"Lorem Ipsn gravida nibh vel velit auctor aliquet.Aenean sollicitudin, Nam nec tellus a odio tincidunt auctor a ornare odio.",
    "duration":"7 weeks",
    "lecture":"12",
    "quizzes" :"4",
    "percentage":"60",
    "maxRetake":"3",
    "certificateDescription":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut hendrerit odio, id suscipit urna."
    },
    
    {
    "id":18,
    "image" :"https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcS_ujQjbuUBF8g2IZV0s1jWXqA-k9gTfwKHLLyw3l38ALT8N0pO",
    "certificate":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUP1wydOPDck6B8Wgeuguri9gedByAl1l4kw&usqp=CAU",
    "course" :"Expository writing",
    "instructor":"Ana Murphy",
    "categories":"Language",
    "Rating":"5",
    "price":"$45",
    "description":"Lorem Ipsn gravida nibh vel velit auctor aliquet.Aenean sollicitudin, Nam nec tellus a odio tincidunt auctor a ornare odio.",
    "duration":"2 weeks",
    "lecture":"10",
    "quizzes" :"3",
    "percentage":"60",
    "maxRetake":"3",
    "certificateDescription":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut hendrerit odio, id suscipit urna."
    },
    
    {
    "id":19,
    "image" :"https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSZ3oW286fRcRr1DdtloaJEEXFUMhNNEu4YcQ2II1iU7WcZljnX",
    "certificate":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUP1wydOPDck6B8Wgeuguri9gedByAl1l4kw&usqp=CAU",
    "course" :"Communication",
    "instructor":"JSophy Janer",
    "categories":"Business",
    "Rating":"5",
    "price":"$20",
    "description":"Lorem Ipsn gravida nibh vel velit auctor aliquet.Aenean sollicitudin, Nam nec tellus a odio tincidunt auctor a ornare odio.",
    "duration":"6 weeks",
    "lecture":"20",
    "quizzes" :"5",
    "percentage":"60",
    "maxRetake":"3",
    "certificateDescription":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut hendrerit odio, id suscipit urna."
    },
    
    {
    "id":20,
    "image" :"https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQ390ts0Kdj0yCpT-keHQv4K7EjG5ZkQpcA-3C1jNk0tM6Nu8BF",
    "certificate":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUP1wydOPDck6B8Wgeuguri9gedByAl1l4kw&usqp=CAU",
    "course" :"Web Security",
    "instructor":"Edy Bowman",
    "categories":"Programming Languages",
    "Rating":"5",
    "price":"Free",
    "description":"Lorem Ipsn gravida nibh vel velit auctor aliquet.Aenean sollicitudin, Nam nec tellus a odio tincidunt auctor a ornare odio.",
    "duration":"5 weeks",
    "lecture":"8",
    "quizzes" :"4",
    "percentage":"60",
    "maxRetake":"2",
    "certificateDescription":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut hendrerit odio, id suscipit urna."
    }
    
    

  ];
  